### ISSUE TITLE
'registration' module does not exist

### ISSUE THREAD

**Issue by MKaras93** [oriefy/shopspot#25]
### Description

(First time contrib here, please don't bite.)
Module 'registration' does not exist (yet) but is already included in settings.py and shopspot/shopspot/urls.py. Makes it impossible to use manage.py and test stuff.

### Steps to Reproduce

1. Clone the repo
2. Run in terminal 'python manage.py makemigrations' or 'python manage.py runserver'
3. You will get an error 'module "registration" does not exist.'.

**Expected behavior:**
'registration' module should be already included in the repo, otherwise it shouldn't be referred to in other files.

**Actual behavior:**

**Reproduces how often:**
100%

### Versions

Python 3.6.6
Django 2.1.2

### Additional Information:
Seems like a partially implemented registration feature.

**Comment by ZeroCoolHacker** [comment]
@MKaras93 Thanks for pointing that out.
