### ISSUE TITLE
Add User Django Model Admin

### ISSUE THREAD

**Issue by ZeroCoolHacker** [oriefy/shopspot#9]
### Description

Add a Proper Django Admin view for the User model.
You can search user by first_name, last_name and email
list view presents necessary information
you can filter users based on user_types i.e is_staff, is_admin, is_buyer, is_seller

**Comment by MKaras93** [comment]
Created a PR for this:
https://github.com/oriefy/shopspot/pull/27

**Comment by ZeroCoolHacker** [comment]
@Mkaras93we appreciate your efforts.
